### ISSUE TITLE
Links to the instrument websites here causes confusion for users

### ISSUE THREAD

**Issue by sosey** [spacetelescope/hst_notebooks#139]
This page starts with the sentence:

> This page provides links to notebooks created by various Hubble Space Telescope instrument teams and software groups, including:

https://spacetelescope.github.io/hst_notebooks/index.html

Expectation are that the links following go to the notebooks, but the links go to the Dox pages for the instruments. 
It's not clear that the user should use the left navigation bar to go to the notebook pages. 

Can this be made more clear? Perhaps add links to the notebooks on the front page here, and if needed make a clear section that says these links go to the general instrument documentation pages?

**Comment by haticekaratay** [comment]
Thanks, @sosey, for highlighting the navigation issue. I've created a ticket for this. You can expect updates soon that will include direct links to the notebooks. We appreciate your input in helping us enhance the site.
