### ISSUE TITLE
Remove Initialization notebook from DrizzlePac repository

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/hst_notebooks#286]
The [Initialization](https://github.com/spacetelescope/hst_notebooks/tree/main/notebooks/DrizzlePac/Initialization) notebook was written before CI was set up and is no longer appropriate. 

Since users can still access the notebook from github, we request that the folder be deleted or moved to a subdirectory for old/outdated content.

**Comment by haticekaratay** [comment]
Thanks, @mackjenn, for the request. As part of our deprecation policy, I will move the notebook to the `deprecated` branch.

**Comment by mackjenn** [comment]
This sounds like a good solution.  Thank you for your assistance!

**Comment by haticekaratay** [comment]
@mackjenn, the Initialization notebook is removed from the main.
