### ISSUE TITLE
Issue on page /notebooks/HASP/DataDiagnostic/DataDiagnostics.html

### ISSUE THREAD

**Issue by wvdixon** [spacetelescope/hst_notebooks#328]
Anna Payne has produced a new version of the HASP Data Diagnostics notebook.  It needs to replace the current version.

The new notebook lives here:  

https://github.com/spacetelescope/hst_notebooks/blob/main/notebooks/HASP/DataDiagnostic/DataDiagnostics.ipynb

**Comment by haticekaratay** [comment]
Hi @wvdixon, 
I see the latest version displayed on GitHub Pages seems to include Anna's updates (https://spacetelescope.github.io/hst_notebooks/notebooks/HASP/DataDiagnostic/DataDiagnostics.html). Are these changes not appearing as you expected? Please let me know if you see any discrepancies. I know @gibsongreen reviewed this notebook, so he might have some insights to share.

**Comment by wvdixon** [comment]
Hmm…  They do appear to be the same version (updated 10/20/2024).  So why did Anna ask me to update the web page?

Sorry to bother you.  – Van


From: Hatice Karatay ***@***.***>
Reply-To: spacetelescope/hst_notebooks ***@***.***>
Date: Tuesday, December 3, 2024 at 4:39 PM
To: spacetelescope/hst_notebooks ***@***.***>
Cc: Van Dixon ***@***.***>, Mention ***@***.***>
Subject: Re: [spacetelescope/hst_notebooks] Issue on page /notebooks/HASP/DataDiagnostic/DataDiagnostics.html (Issue #328)


Hi @wvdixon<https://urldefense.com/v3/__https:/github.com/wvdixon__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!0vxXsCxJEGwWvCvnQeJesq3l8ki2Xmwk-Sk-f3nhlegEEWCHjprYOk1BQx_5elPNZaet3nPsqLvv2RDc5L54040$>,
I see the latest version displayed on GitHub Pages seems to include Anna's updates (https://spacetelescope.github.io/hst_notebooks/notebooks/HASP/DataDiagnostic/DataDiagnostics.html<https://urldefense.com/v3/__https:/spacetelescope.github.io/hst_notebooks/notebooks/HASP/DataDiagnostic/DataDiagnostics.html__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!0vxXsCxJEGwWvCvnQeJesq3l8ki2Xmwk-Sk-f3nhlegEEWCHjprYOk1BQx_5elPNZaet3nPsqLvv2RDct_CEFaU$>). Are these changes not appearing as you expected? Please let me know if you see any discrepancies. I know @gibsongreen<https://urldefense.com/v3/__https:/github.com/gibsongreen__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!0vxXsCxJEGwWvCvnQeJesq3l8ki2Xmwk-Sk-f3nhlegEEWCHjprYOk1BQx_5elPNZaet3nPsqLvv2RDcoUkcn9A$> reviewed this notebook, so he might have some insights to share.

**Comment by gibsongreen** [comment]
Hey @wvdixon ,

If any additional updates are needed for this notebook please feel free to tag me here or reach out to me. Just a heads up that there is a soft freeze date for notebook repositories on December 10 for AAS, but I am happy to implement any changes necessary after that date!

- Gilbert

**Comment by haticekaratay** [comment]
@wvdixon
No worries. I'm glad your question has been clarified.
